GET http://localhost:4017/api

###

GET http://localhost:4017/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjpbeyJpZCI6MSwidXNlcm5hbWUiOiJPd2V0aHVTb3RvbWVsYSJ9XSwiaWF0IjoxNjUwNTMzOTIyLCJleHAiOjE2NTA2MjAzMjJ9.kgcpxzQNec2KeI9G-KemB2t5V1s27gJfjemFa1HKCWk

###

POST http://localhost:4017/api/login
Content-Type: application/json

{
    "username": "OwethuSotomela"
}